name = "love-vibes-frontend"
compatibility_date = "2025-01-18"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://lovevibes.thelovevibes-ai.workers.dev"
