name = "love-vibes-frontend"
compatibility_date = "2026-01-26"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://lovevibes.thelovevibes-ai.workers.dev"
